### ISSUE TITLE
Unable to download

### ISSUE THREAD

**Issue by angelborn** [peregrine-collegia/POD#5]
when I click the download link it takes me to dropbox and then tells me there is no file. has it been pulled, or is there something wrong with the link?

**Comment by flintsparc** [comment]
I'll be loading a new one today

**Comment by flintsparc** [comment]
New file.

Enjoy:
https://www.dropbox.com/s/419oqnbbb7nasu6/Princes_of_Darkness_v_0.3.0.zip?dl=0

**Comment by flintsparc** [comment]
I have heard your whims from the priority poll, and I obey!

New download! Version 0.3.0 April 8.2017.
<https://forum.paradoxplaza.com/forum/index.php?attachments/princes_of_darkness_v-0-3-0-zip.254110/>

1230 bookmark returns! Major European Feudal Empires. Eighteen canon
characters available. Each of the 13 clans has a character available, plus
one for the Baali.

[image: [​IMG]]

War of Princes Era Character Chooser

   - Mithras <http://whitewolf.wikia.com/wiki/Mithras>, Ventrue, 4th
   generation, Saxon (originally Persian), Baronies of Avalon
   - High Lord Hardestadt the Elder
   <http://whitewolf.wikia.com/wiki/Hardestadt_the_Elder>, Ventrue, 5th
   generation, German, Fiefs of the Black Cross
   - Queen Salianna <http://whitewolf.wikia.com/wiki/Salianna>, Toreador,
   5th generation, Matriarch of the Courts of love
   - Montano <http://whitewolf.wikia.com/wiki/Montano>, Lasombra, 4th
   generation, Emperor of the Sea of Shadows
   - Vladimir Rustovich <http://whitewolf.wikia.com/wiki/Vladimir_Rustovich>,
   Tzimisce, 6th generation, Koldun, Voivode of Voivodes
   - Guillaume <http://whitewolf.wikia.com/wiki/Guillaume>, Brujah, 5th
   generation, Inconnu, Prince of Switzerland

War of Princes Era Selected Characters

   - Bulscu Arpad <http://whitewolf.wikia.com/wiki/Bulscu>, Ventrue, 6th
   generation, King of Hungary
   - Augustus Giovanni <http://whitewolf.wikia.com/wiki/Augustus_Giovanni>,
   Cappadocian, 4th generation, Patriarch of the Giovanni
   - Lotharius <http://whitewolf.wikia.com/wiki/Lotharius>, Tremere, 5th
   generation, Prince of Vienna (independent of the Fiefs of the Black Cross)
   - Lord Jürgen of Magdeburg
   <http://whitewolf.wikia.com/wiki/J%C3%BCrgen_of_Madgeburg> “the
   sword-bearer”, Ventrue, 6th generation, Prince of Magdburg/Bradenburg,
   Fiefs of the Black Cross
   - Josef Zvi <http://whitewolf.wikia.com/wiki/Josef_Zvi>, Nosferatu,
   Prince of Prague, (independent of the Fiefs of the Black Cross)
   - Werter, Gangrel, 7th Generaiton, Prince of Uppsala, Einherjar
   <http://whitewolf.wikia.com/wiki/Einherjar>
   - Midian, Malkavian, Prince of Hamburg, (independent of the Fiefs of the
   Black Cross)
   - Bela Rusenko <http://whitewolf.wikia.com/wiki/Bela_Rusenko>,
   Cappadocian, 7th Generation, Road of Sin, Prince of Sofia, Bulgaria
   - Etienne de Faubergé
   <http://whitewolf.wikia.com/wiki/Etienne_de_Fauberg%C3%A9>, Ravnos, 7th
   generation, Prince of Akre
   - Sha'hiri <http://whitewolf.wikia.com/wiki/Sha%27hiri>, Assamite, 4th
   Generation, Eldest of Alamut, Old Man of the Mountain
   - Nakhthorheb <http://whitewolf.wikia.com/wiki/Nakhthorheb>, Follower of
   Set, 4th generation, Pharaoh of Giza, Leader of the Followers of Set
   - Tanith <http://whitewolf.wikia.com/wiki/Tanit>, Baali, 5th Generation,
   Secret Prince of Tyre

Wiki entries available in game.

[image: [​IMG]]

Dynasties in Europe in 1230 AD

[image: [​IMG]]

Sometimes there is a crash in the first few years. Reload from last save (I
save monthly, and recommend you do so as well). After that, though, the
game runs smoothly.

Year 1338 AD in a 1230 AD play through:

[image: [​IMG]]

Change log
Version 0.3.0

After the release of Monks & Mystics, we decided to use new code options
like scripted_effects and scripted_triggers. This meant a substantial
rewrite of some code to make it more modular. Startup is faster. Game play
is faster thanks to on_action events and pre_triggers.
Vampires, mummies, prometheans and geists no longer get illness or disease.
We may add in some supernatural diseases for them in the future.
Added darker colormapp.dds from Darker Map mod.
Added back Caine and the Antediluvians to Masquerade bookmarks.
Added back Classic World of Darkness Dark Ages Vampire Characters.
Added back War of Princes 1230 Bookmark.
Title History work for War of Princes 1230 Bookmark.
Various code shenanigans to have AIs have dynasties other than "generic".
Changes Giovanni Empire shield to DAV20 design.
Disabled vanilla holy orders.
Disabled vanilla crusades.
Covenant (Holy) Wars are now called Jyhads.
Iconnu and Oradea League now pacifist.
Cappadocian dynasties.
