### ISSUE TITLE
missing symbol

### ISSUE THREAD

**Issue by Australopitecus** [peregrine-collegia/POD#6]
Hi, 

In v0.3.3.1 

common\scripted_effects\POD_CWOD_vampire_disciplines_init_effect.txt

I think the Gangrel has a missing " **}** ". 

At the end of "neonate" it looks like this:
10 = {
	add_trait = resilience_3
	}
}
					
if = {

Could it be that it should look like this?

10 = {
	add_trait = resilience_3
	}
}
}
if = {

I'm sorry if I'm too abstract I don't know sh.t about this stuff so don't know how to explain it. Gangrel had a problem with disciplines so I just compared it with the rest to see if there was a difference, I made the change and it worked, luckily.

Thanks for the mod! it's amazing!

**Comment by flintsparc** [comment]
Good bug hunt!  I'll implement this fix.  A single missing } can cause a
lot of trouble.

However, I think your fix would cause additional trouble with the } before
# Assamite, so I removed that one.   You probably need to do that to in
your copy of the mod until I release the fix.

How should I credit out in the changelong?  as Australopitecus?   If you've
already understood my code enough to find this bug, I imagine you'll
probably fix other things in the future :)

**Comment by Australopitecus** [comment]
You are right!! The disciplines not showing jumped to Assamite xD. Deleting that last one before 
# Assamite fixed it back like you said. Now all clans spawn with disciplines. 

About the credit is not necessary, the only thing I did was to compare it with another clan with antitribu.

Thanks anyway.
